// Editorial content for the AI Learning Hub.
// Update this file without changing the site's layout in index.html.
window.DRAGON_LEARNING = {
  reviewedOn: 'September 2, 2026',
  currentReviewedAt: '2026-09-02',
  evergreenReviewedAt: '2026-09-02',
  sourcesReviewedAt: '2026-09-02',
  toolsReviewedAt: '2026-09-02',
  connectionsReviewedAt: '2026-09-02',
  currentPicks: [
    {title:'As AI travel discovery moves, who keeps the booking?',source:'Everything AI in Travel · Tony Carne',url:'https://everythingaiintravel.beehiiv.com/p/as-ai-travel-discovery-moves-who-keeps-the-booking',format:'read',label:'new',time:'6 min',published:'October 9, 2026',tags:['findability','agents','operations'],why:'The direct-booking question every small operator faces as AI assistants become the front door to travel discovery.',next:'List where guests currently book you, then note which of those steps an AI assistant could take over.'},
    {title:'What happens to community-based tourism if AI becomes how travellers discover and book',source:'Everything AI in Travel · Tony Carne',url:'https://everythingaiintravel.beehiiv.com/p/new-podcast-what-happens-to-community-based-tourism-if-ai-becomes-the-new-way-travellers-discover-an',format:'listen',label:'new',time:'Podcast',published:'September 30, 2026',tags:['findability','agents'],why:'Small, local operators are the subject, so the discovery and booking questions apply to a boutique tour business directly.',next:'Note one thing that makes your tours bookable without a middleman, and check an AI assistant can find it.'},
    {title:'Using AI to build a single API for multi-day touring',source:'Everything AI in Travel · Tony Carne with Thomas Bangert',url:'https://everythingaiintravel.beehiiv.com/p/new-podcast-thomas-bangert-is-using-ai-to-build-the-single-api-for-multi-day-touring',format:'listen',label:'new',time:'Podcast',published:'September 15, 2026',tags:['agents','operations'],why:'Multi-day products are hard to distribute and describe to machines, which is the everyday problem for walking and touring operators.',next:'Write your itinerary as structured facts (days, distances, inclusions) and see how an assistant summarises it.'},
    {title:'Did Anthropic just level the playing field in travel with its commerce agents?',source:'Everything AI in Travel · Tony Carne',url:'https://everythingaiintravel.beehiiv.com/p/did-anthropic-just-level-the-playing-field-in-travel-with-its-commerce-agents',format:'read',label:'current',time:'6 min',published:'September 11, 2026',tags:['agents','findability'],why:'A look at whether AI agents let small operators compete with the large online travel agencies.',next:'Decide what you would want an AI agent to be allowed to say or book on your behalf, and what needs a human.'},
    {title:'The Last Free Booking: what works now with creators, social search and AI',source:'Tourpreneur podcast · Ep. 335',url:'https://tourpreneur.com/podcast/',format:'listen',label:'current',time:'Podcast',published:'latest episodes (see page for dates)',tags:['marketing','findability'],why:'A weekly show made for tour operators; this episode, and Ep. 334 on AI, cover discovery through social search and AI.',next:'Pick one idea you can try on your own channels this month.'},
    {title:'GPT 6 Astra: AI just took the mouse',source:'Untangling Tourism Tech · Tourism Tribe · Ep. 22',url:'https://podcasts.apple.com/au/podcast/untangling-tourism-tech/id1747634430',format:'listen',label:'new',time:'Podcast',published:'October 2026',tags:['agents','operations'],why:'Explains what ChatGPT now doing computer tasks means for operators, what it costs, and what to have in place first.',next:'Write down two tasks you would hand to an AI that clicks through websites, and two you would not.'},
    {title:'ChatGPT for Small Business: Workshop Resource Hub',source:'OpenAI Academy · Calvin Landrum',url:'https://academy.openai.com/public/resources/openai-academy-small-business-resource-hub-2026-06-03',format:'watch',label:'current',time:'30–60 min',published:'updated August 5, 2026',tags:['operations','marketing'],why:'A practical set of prompts, exercises, and guardrails for turning a real small-business task into a reusable workflow.',next:'Bring one recurring task and rewrite its prompt using Goal, Context, Output, and Boundary.'}
  ],
  evergreen: [
    {title:'AI Fluency: Framework & Foundations',source:'Anthropic',url:'https://academy.claude.com/courses/ai-fluency-framework-foundations',format:'watch',label:'essential',time:'About 4 hrs',published:'evergreen course',tags:['foundations','safety'],why:'A durable framework for deciding what to delegate to AI, describing the work clearly, judging results, and using AI responsibly.',next:'Use the four-part framework—Delegation, Description, Discernment, and Diligence—on one real travel task.'},
    {title:'Responsible use of ChatGPT at work',source:'OpenAI Academy',url:'https://academy.openai.com/public/clubs/work-users-ynjqu/resources/responsible-use-of-chatgpt-at-work-2025-09-08',format:'read',label:'essential',time:'8 min',published:'updated May 29, 2026',tags:['safety'],why:'A focused, plain-language guide to privacy, human oversight, bias, verification, consent, and responsible use in everyday work.',next:'Use its checklist to set three rules for what your team will never upload, what must be verified, and what always needs human approval.'},
    {title:'AI features and your website',source:'Google Search Central',url:'https://developers.google.com/search/docs/appearance/ai-features',format:'read',label:'reference',time:'10 min',published:'updated December 10, 2025',tags:['findability'],why:'Google\'s own explanation of how AI Overviews and AI Mode pick links; it says no special AI optimisation is required, which is a useful check on vendor claims.',next:'Confirm your pages are indexable, your key facts are in plain text, and structured data matches what visitors see.'},
    {title:'AI capabilities and limitations',source:'Claude Academy · Anthropic',url:'https://academy.claude.com/courses/ai-capabilities-and-limitations',format:'watch',label:'essential',time:'About 3.5 hrs',published:'evergreen course',tags:['foundations','safety'],why:'Builds a working mental model of what language models can and cannot do, including context limits.',next:'Use it to write down three tasks you will always verify by hand.'},
    {title:'Elements of AI',source:'University of Helsinki + MinnaLearn',url:'https://www.elementsofai.com/',format:'read',label:'essential',time:'Self-paced',published:'evergreen course',tags:['foundations'],why:'A nontechnical foundation for understanding what AI is, what it can do, and where its limitations begin.',next:'Complete the introduction before evaluating new AI tools or vendor claims.'},
    {title:'But what is a neural network?',source:'3Blue1Brown',url:'https://www.youtube.com/watch?v=aircAruvnKk',format:'watch',label:'essential',time:'19 min',published:'October 5, 2017',tags:['foundations'],why:'The visuals make a difficult core idea understandable without requiring code or advanced mathematics.',next:'Watch for the distinction between the inputs, hidden layers, and the final prediction.'},
    {title:'An opinionated guide to which AI to use to do stuff',source:'One Useful Thing · Ethan Mollick',url:'https://www.oneusefulthing.org/p/an-opinionated-guide-to-which-ai-b22',format:'read',label:'essential',time:'15 min',published:'July 23, 2026',tags:['foundations'],why:'A current, plain-language guide to choosing between assistants and their modes for real work.',next:'Match one of your recurring tasks to the tool and mode it recommends, then compare with what you use now.'},
    {title:'Getting Found in the AI Age: A Guide for Operators',source:'Arival · Oliver Green',url:'https://arival.travel/article/getting-found-in-the-ai-age-a-guide-for-operators/',format:'read',label:'reference',time:'15 min',published:'March 30, 2026',tags:['findability','marketing'],why:'A clear operator-level introduction to AI search, answer-engine optimization, third-party signals, and zero-click discovery.',next:'Search for your business as a traveler would and record which sources the answer cites—not only whether your website appears.'},
    {title:'Storytelling as a Competitive Advantage in the Age of AI',source:'Tourpreneur · Mitch Bach with Iain Manley',url:'https://tourpreneur.com/storytelling-as-a-competitive-advantage-in-the-age-of-ai/',format:'listen',label:'essential',time:'Podcast',published:'March 17, 2026',tags:['marketing'],why:'Personal perspective, specificity, and a real sense of place remain strong travel differentiators as generic AI content multiplies.',next:'Review one tour description or guide script and add a detail that could only come from firsthand knowledge.'}
  ],
  aiTools: [
    {name:'ChatGPT',company:'OpenAI',type:'General assistant',recommended:true,url:'https://chatgpt.com/',learnUrl:'https://academy.openai.com/',best:'A versatile first assistant for writing, planning, files, images, research, projects, and connected work.',start:'Bring one real recurring task. Give it a goal, context, desired output, and a clear boundary.'},
    {name:'Claude',company:'Anthropic',type:'General assistant',recommended:true,url:'https://claude.ai/',learnUrl:'https://academy.claude.com/collections/claude-for-you',best:'Thoughtful work with long documents, analysis, writing, projects, and creating useful artifacts.',start:'Upload a non-sensitive document and ask for a summary, unanswered questions, and a fact-check list.'},
    {name:'Gemini',company:'Google',type:'General assistant',recommended:false,url:'https://gemini.google.com/',learnUrl:'https://support.google.com/gemini/answer/13275745?hl=en',best:'People who already work in the Google ecosystem and want an assistant for ideas, research, files, and media.',start:'Ask it to compare three ways to solve a familiar work problem, then verify the factual claims.'},
    {name:'Perplexity',company:'Perplexity',type:'Answer engine',recommended:true,url:'https://www.perplexity.ai/',learnUrl:'https://www.perplexity.ai/help-center/en/articles/10354975-getting-started-with-perplexity',best:'Current web research, exploring a question, following citations, and building a sourced starting point.',start:'Research one current travel question. Open at least three cited sources and note what the answer missed.'},
    {name:'Microsoft Copilot',company:'Microsoft',type:'Work assistant',recommended:false,url:'https://copilot.com/',learnUrl:'https://support.microsoft.com/en-us/microsoft-365-copilot/get-started-with-microsoft-365-copilot-chat',best:'People whose daily work already lives in Microsoft 365, Outlook, Word, Excel, PowerPoint, or Teams.',start:'Use a low-risk draft or document and ask Copilot to summarize it, identify gaps, and suggest next steps.'},
    {name:'Gemini Notebook (formerly NotebookLM)',company:'Google',type:'Source-grounded research',recommended:false,url:'https://notebook.google/',learnUrl:'https://support.google.com/gemininotebook/answer/16164461?hl=en',best:'Learning from a defined collection of your own sources, with citations, study guides, and audio overviews.',start:'Create a notebook with two trusted sources and ask for agreements, disagreements, and cited takeaways.'}
  ],
  suggestedPath: [
    {name:'AI Fluency: Framework & Foundations',creator:'Anthropic',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',note:'Start with a durable framework for delegating, describing, judging, and responsibly using AI.'},
    {name:'Elements of AI',creator:'University of Helsinki + MinnaLearn',url:'https://www.elementsofai.com/',note:'Build a nontechnical foundation for what AI can and cannot do.'},
    {name:'Introduction to Generative AI',creator:'Google',url:'https://www.skills.google/course_templates/536',note:'Use a short primer to distinguish generative AI from earlier forms of machine learning.'},
    {name:'OpenAI Academy',creator:'OpenAI',url:'https://academy.openai.com/',note:'Practice applying an assistant to real work with current first-party instruction.'},
    {name:'AI for Marketers',creator:'HubSpot Academy',url:'https://academy.hubspot.com/courses/AI-for-Marketers',note:'Apply AI to content, email, social, and campaign work.'},
    {name:'Generative AI for Everyone',creator:'DeepLearning.AI · Andrew Ng',url:'https://www.coursera.org/learn/generative-ai-for-everyone',note:'Finish with a calm business-strategy view of where generative AI creates value.'}
  ],
  glossary: [
    {term:'Artificial intelligence (AI)',definition:'The broad field of making computers perform tasks that normally require human-like perception, language, prediction, or decision-making.'},
    {term:'Generative AI',definition:'AI that creates new material—such as text, images, audio, video, or code—based on patterns learned from examples.'},
    {term:'Large language model (LLM)',definition:'A model trained on large amounts of language so it can interpret and generate text. It predicts plausible language; it does not “know” facts the way a person does.'},
    {term:'Model',definition:'The underlying trained system. A product such as ChatGPT may offer several models with different strengths, speeds, or limits.'},
    {term:'AI assistant',definition:'The product interface you talk to, such as ChatGPT, Claude, or Gemini. The assistant can combine a model with tools, memory, files, and safety controls.'},
    {term:'Multimodal',definition:'Able to work with more than one kind of input or output, such as text, images, audio, or video.'},
    {term:'Prompt',definition:'The instruction, question, examples, files, and context you give an AI. A useful prompt states the goal, relevant context, desired output, and boundaries.'},
    {term:'Context',definition:'The information available to the model for the current task, including your prompt, conversation, attached files, and permitted connected data.'},
    {term:'Context window',definition:'The amount of information a model can consider at one time. Older or less relevant material may fall outside it in very long conversations.'},
    {term:'Token',definition:'A small chunk of text processed by a model. Usage limits and context windows are often measured in tokens rather than words.'},
    {term:'Hallucination',definition:'A confident-sounding AI statement that is unsupported, invented, or incorrect. Important facts should be checked against reliable sources.'},
    {term:'Grounding',definition:'Tying an answer to supplied files, reliable web sources, or connected data instead of relying only on the model’s general training.'},
    {term:'Retrieval / RAG',definition:'Finding relevant information first and giving it to the model to use in its answer. RAG stands for retrieval-augmented generation.'},
    {term:'Agent',definition:'An AI system that can plan steps and use tools to pursue an outcome, often with checkpoints or approvals. More autonomy requires clearer boundaries and review.'},
    {term:'Connection / connector',definition:'An authorized link between an AI assistant and another service, allowing supported reading, searching, syncing, or actions within the permissions granted.'},
    {term:'Plugin',definition:'A packaged workflow that can add instructions, connected apps, or tools to ChatGPT or Codex. Installing it does not automatically grant access to an outside account.'},
    {term:'Skill',definition:'Reusable instructions that teach an AI how to perform a particular kind of task consistently. A skill may not require any outside connection.'},
    {term:'MCP',definition:'Model Context Protocol—a standard that lets AI products use approved external tools and information through a defined connection.'},
    {term:'API',definition:'A structured way for one piece of software to request data or actions from another. APIs are commonly used to put AI inside an app or workflow.'},
    {term:'Memory',definition:'Information an AI product may retain to personalize future conversations. Memory controls, scope, and availability vary by product and account.'},
    {term:'Deep research',definition:'A longer research workflow in which an AI searches multiple sources, synthesizes findings, and usually provides citations for review.'},
    {term:'Fine-tuning',definition:'Additional training that adapts a model to examples of a specific task or style. Most beginners do not need fine-tuning to use AI effectively.'}
  ],
  trustedSources: [
    {name:'Everything AI in Travel',kind:'podcast',url:'https://www.everythingaiintravel.com/blog',note:'Travel-specific interviews, analysis, and practical operator examples.'},
    {name:'Travel Trends Podcast',kind:'podcast',url:'https://www.traveltrendspodcast.com/',note:'B2B conversations about discovery, booking, distribution, and travel technology.'},
    {name:'Tourpreneur',kind:'podcast',url:'https://tourpreneur.com/podcast/',note:'Grounded operator conversations about marketing, operations, and guest experience.'},
    {name:'In Phocus',kind:'podcast',url:'https://www.phocuswire.com/In-Phocus-Podcast',note:'Travel-tech news and interviews from PhocusWire.'},
    {name:'The AI Daily Brief',kind:'podcast',url:'https://aidailybrief.ai/',note:'Fast context on major AI changes; individual episodes are vetted before featuring.'},
    {name:'3Blue1Brown',kind:'youtube',url:'https://www.youtube.com/@3blue1brown',note:'Exceptional visual explanations of neural networks and machine learning foundations.'},
    {name:'DeepLearning.AI',kind:'youtube',url:'https://www.youtube.com/@Deeplearningai',note:'Short explainers, interviews, and selected practical AI lessons.'},
    {name:'Andrej Karpathy',kind:'youtube',url:'https://www.youtube.com/@AndrejKarpathy',note:'Long-form, build-from-first-principles explanations for deeper technical learning.'},
    {name:'Two Minute Papers',kind:'youtube',url:'https://www.youtube.com/@TwoMinutePapers',note:'Accessible summaries of new AI research; use for orientation, not business decisions.'},
    {name:'One Useful Thing',kind:'newsletter',url:'https://www.oneusefulthing.org/',note:'Evidence-led guidance for using AI thoughtfully at work.'},
    {name:'Travel Tech Essentialist',kind:'newsletter',url:'https://traveltechessentialist.substack.com/',note:'Travel-platform, investment, and technology-shift analysis.'},
    {name:'AI Snake Oil',kind:'newsletter',url:'https://www.normaltech.ai/',note:'A valuable skeptical lens for evaluating AI claims and risks.'},
    {name:'The Batch',kind:'newsletter',url:'https://www.deeplearning.ai/the-batch/',note:'Weekly expert framing of important AI developments.'},
    {name:'OpenAI Academy',kind:'learning',url:'https://academy.openai.com/',note:'Current first-party learning for ChatGPT, Codex, work, and small business.'},
    {name:'Anthropic AI Fluency',kind:'learning',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',note:'A practical, model-independent framework for collaborating with AI.'},
    {name:'Elements of AI',kind:'learning',url:'https://www.elementsofai.com/',note:'A durable, nontechnical introduction to AI.'},
    {name:'Arival',kind:'web',url:'https://arival.travel/',note:'Research and practical guidance for tours, activities, attractions, and experiences.'},
    {name:'PhocusWire',kind:'web',url:'https://www.phocuswire.com/',note:'Travel technology, distribution, platforms, and industry analysis.'}
    ,{name:'The Artificial Intelligence Show',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/the-artificial-intelligence-show/id1548733275',note:'Paul Roetzer and Mike Kaput translate weekly AI news into practical business implications with unusually consistent, relevant analysis.'}
    ,{name:'AI-Driven Marketer',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/ai-driven-marketer-master-practical-ai-marketing-skills/id1719663520',note:'Dan Sanchez shares practical AI marketing tools, workflows, copy, and campaign lessons.'}
    ,{name:'Small Business Big AI',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/small-business-big-ai/id1768659876',note:'Kim Lewis Howard focuses on strategy, governance, and high-value AI workflows for small businesses.'}
    ,{name:'Matt Wolfe',kind:'youtube',url:'https://www.youtube.com/@mreflow',note:'Matt Wolfe publishes frequent visual roundups of new AI tools and releases; use recent videos for orientation, then verify product claims.'}
    ,{name:'Superhuman AI',kind:'newsletter',url:'https://www.superhuman.ai/',note:'Zain Kahn and the Superhuman team publish a short daily briefing on AI tools and news.'}
    ,{name:'Sabrina Ramonov',kind:'youtube',url:'https://www.youtube.com/@SabrinaRamonov',note:'Sabrina Ramonov shares prompts, playbooks, and automation systems suited to solo operators and lean teams.'}
    ,{name:'Behind the Craft',kind:'newsletter',url:'https://creatoreconomy.so/',note:'Peter Yang writes hands-on AI and go-to-market tutorials, including practical campaigns and workflows.'}
    ,{name:'GEO: How to rank in AI search',kind:'web',url:'https://llmpulse.ai/blog/geo-guide/',note:'LLM Pulse provides a second, practical view of visibility in generative search engines.'}
    ,{name:'Schema Markup Guide for SEO and AI Search',kind:'web',url:'https://discoverability.co/guides/beginners-guide-to-schema-markup/',note:'Discoverability explains structured data and the schema types most useful for machine-readable business information.'}
    ,{name:'Julian Goldie',kind:'youtube',url:'https://www.youtube.com/@JulianGoldieSEO',note:'Julian Goldie publishes frequent, practical videos about AI SEO, schema, and content workflows; verify fast-changing tactics before adopting them.'}
    ,{name:'Nate Herk',kind:'youtube',url:'https://www.youtube.com/@nateherk',note:'Nate Herk demonstrates end-to-end AI automations with n8n, making agent workflows visible and concrete.'}
    ,{name:'How Generative AI Is Revolutionizing Travel and Tourism',kind:'web',url:'https://arival.travel/article/generative-ai-in-travel-tourism/',note:'Arival gives travel-specific examples of personalization, itinerary building, and AI assistance for travelers.'}
    ,{name:'Travel Trends for Tour Operators',kind:'web',url:'https://www.rezgo.com/blog/global-travel-trends-2026-what-tour-and-activity-operators-need-to-know/',note:'Rezgo offers an operator-focused view of AI and demand trends for tours and activities.'}
    ,{name:'Adventure Travel Education',kind:'web',url:'https://learn.adventuretravel.biz/education/',note:'The Adventure Travel Trade Association publishes education grounded in the adventure-travel community.'}
    ,{name:"There's An AI For That",kind:'web',url:'https://theresanaiforthat.com/',note:'A broad discovery directory for exploring AI tools; evaluate privacy, cost, and credibility before adopting anything listed.'}
    ,{name:'FutureTools',kind:'web',url:'https://www.futuretools.io/',note:'Matt Wolfe curates AI tools and news for quick discovery; verify current product details at the original source.'}
    ,{name:'Product Hunt: Artificial Intelligence',kind:'web',url:'https://www.producthunt.com/topics/artificial-intelligence',note:'A high-volume discovery feed for new AI products; useful for scanning, not as a quality endorsement.'}
    ,{name:'The Rundown AI',kind:'newsletter',url:'https://www.therundown.ai/',note:'A frequent, concise AI-news briefing for maintaining awareness of major releases.'}
    ,{name:"Ben's Bites",kind:'newsletter',url:'https://bensbites.com/',note:'Ben Tossell shares frequent AI product and workflow discoveries with a practical builder perspective.'}
    ,{name:'Introduction to Generative AI',kind:'learning',url:'https://www.skills.google/course_templates/536',note:'Google provides a short first-party introduction to generative AI and how it differs from traditional machine learning.'}
    ,{name:'AI for Marketers',kind:'learning',url:'https://academy.hubspot.com/courses/AI-for-Marketers',note:'HubSpot Academy teaches practical AI uses for content, email, social media, and campaign reporting.'}
    ,{name:'Generative AI for Everyone',kind:'learning',url:'https://www.coursera.org/learn/generative-ai-for-everyone',note:'Andrew Ng and DeepLearning.AI explain generative AI through a nontechnical business-strategy lens.'}
    ,{name:'Untangling Tourism Tech',kind:'podcast',url:'https://podcasts.apple.com/au/podcast/untangling-tourism-tech/id1747634430',note:'Tourism Tribe\'s show on practical AI and technology for tourism operators and destinations.'}
    ,{name:'Google: AI features and your website',kind:'web',url:'https://developers.google.com/search/docs/appearance/ai-features',note:'Google\'s official guidance on appearing in AI Overviews and AI Mode.'}
    ,{name:'Google Business Profile Help',kind:'web',url:'https://support.google.com/business',note:'Official help for the profile that AI answers about local businesses may draw on; verify how it affects your listings.'}
    ,{name:'Claude Academy',kind:'learning',url:'https://academy.claude.com/',note:'Anthropic\'s free courses on AI fluency, capabilities and limits, and working with agents.'}
    ,{name:'Phocuswright research updates',kind:'web',url:'https://phocuswright.com/Travel-Research/Research-Updates/2026/61-of-travel-business-surveyed-experimenting-with-or-scaling-agentic-ai',note:'Primary travel-industry research on how businesses are adopting agentic AI.'}
    ,{name:'Generative Engine Optimization: Complete Guide',kind:'web',url:'https://www.enrichlabs.ai/blog/generative-engine-optimization-geo-complete-guide-2026',note:'Enrich Labs explains how GEO differs from SEO and what can help a source earn citations in AI answers.'}
    ,{name:'Best AI agents for marketing',kind:'web',url:'https://www.tofuhq.com/post/best-ai-agents-for-marketing',note:'Tofu HQ maps marketing-agent tools to their likely jobs; treat the vendor landscape as time-sensitive.'}
    ,{name:'Structured Data for AI Search',kind:'web',url:'https://www.stackmatix.com/blog/structured-data-ai-search',note:'Stackmatix shows how JSON-LD is generated and added to a website.'}
  ]
};
