// Editorial content for the AI Learning Hub.
// Update this file without changing the site's layout in index.html.
window.DRAGON_LEARNING = {
  reviewedOn: 'September 2, 2026',
  currentReviewedAt: '2026-09-02',
  evergreenReviewedAt: '2026-09-02',
  sourcesReviewedAt: '2026-09-02',
  toolsReviewedAt: '2026-09-02',
  connectionsReviewedAt: '2026-09-02',
  currentPicks: [
    {title:'How agentic booking could change travel infrastructure',source:'Everything AI in Travel · Tony Carne with Kevin Gautier',url:'https://everythingaiintravel.beehiiv.com/p/new-podcast-kevin-gautier-from-jinko-lays-out-the-world-of-agentic-booking-in-travel',format:'listen',label:'new',time:'Podcast',published:'September 1, 2026',tags:['agents','operations'],why:'A travel-native conversation about the infrastructure AI agents need before they can search and book reliably—not a generic prediction about bots.',next:'Listen for one constraint your business should account for before trusting an automated booking workflow.'},
    {title:'Five practical ways to improve a travel business with Claude',source:'Everything AI in Travel · Tony Carne with Oliver Green',url:'https://everythingaiintravel.beehiiv.com/p/new-podcast-oliver-green-breaks-down-5-practical-things-you-can-do-right-now-to-improve-your-busines',format:'listen',label:'new',time:'Podcast',published:'August 17, 2026',tags:['operations','marketing'],why:'Concrete, operator-focused experiments make this a useful bridge between hearing about AI and applying it to everyday travel work.',next:'Choose one experiment, try it with non-sensitive information, and note whether it saves time or improves quality.'},
    {title:'ChatGPT for Small Business: Workshop Resource Hub',source:'OpenAI Academy · Calvin Landrum',url:'https://academy.openai.com/public/resources/openai-academy-small-business-resource-hub-2026-06-03',format:'watch',label:'current',time:'30–60 min',published:'updated August 5, 2026',tags:['operations','marketing'],why:'A practical set of prompts, exercises, and guardrails for turning a real small-business task into a reusable workflow.',next:'Bring one recurring task and rewrite its prompt using Goal, Context, Output, and Boundary.'},
    {title:'Will AI finally “connect the trip”?',source:'Everything AI in Travel · Tony Carne',url:'https://www.everythingaiintravel.com/blog/post_9d197621-8293-44ee-b6f9-cb335c73ec3e',format:'read',label:'current',time:'8 min',published:'August 13, 2026',tags:['findability','agents','operations'],why:'It separates broad AI-travel adoption headlines from the specific discovery, comparison, and booking behaviors that affect business decisions.',next:'Identify which part of your customer journey—discovery, comparison, booking, or in-trip help—AI is most likely to change first.'},
    {title:'Travel visibility, trust and conversion in agentic commerce',source:'PhocusWire · Abby Crotty',url:'https://www.phocuswire.com/news/distribution/phocuswright-europe-2026-travel-agentic-commerce',format:'watch',label:'current',time:'10 min + session',published:'July 8, 2026',tags:['findability','agents'],why:'A grounded industry discussion of AI visibility, human confirmation, accountability, and why travel adoption is still uneven.',next:'Write down where a human must confirm an AI-assisted recommendation or transaction in your own customer journey.'},
    {title:'How to get your experiences recommended by AI',source:'Arival · Oliver Green',url:'https://arival.travel/article/ai-that-works-getyourguide-report-highlights/',format:'read',label:'current',time:'12 min',published:'June 16, 2026',tags:['findability','marketing','operations'],why:'Travel-experience research is translated into practical steps for listings, content, operations, reviews, and human oversight.',next:'Test whether your experience appears in three AI assistants, then improve one listing’s facts, inclusions, and FAQs.'}
  ],
  evergreen: [
    {title:'AI Fluency: Framework & Foundations',source:'Anthropic',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',format:'watch',label:'essential',time:'2–3 hrs',published:'evergreen course',tags:['foundations','safety'],why:'A durable framework for deciding what to delegate to AI, describing the work clearly, judging results, and using AI responsibly.',next:'Use the four-part framework—Delegation, Description, Discernment, and Diligence—on one real travel task.'},
    {title:'Responsible use of ChatGPT at work',source:'OpenAI Academy',url:'https://academy.openai.com/public/clubs/work-users-ynjqu/resources/responsible-use-of-chatgpt-at-work-2025-09-08',format:'read',label:'essential',time:'8 min',published:'updated May 29, 2026',tags:['safety'],why:'A focused, plain-language guide to privacy, human oversight, bias, verification, consent, and responsible use in everyday work.',next:'Use its checklist to set three rules for what your team will never upload, what must be verified, and what always needs human approval.'},
    {title:'Elements of AI',source:'University of Helsinki + MinnaLearn',url:'https://www.elementsofai.com/',format:'read',label:'essential',time:'Self-paced',published:'evergreen course',tags:['foundations'],why:'A nontechnical foundation for understanding what AI is, what it can do, and where its limitations begin.',next:'Complete the introduction before evaluating new AI tools or vendor claims.'},
    {title:'But what is a neural network?',source:'3Blue1Brown',url:'https://www.youtube.com/watch?v=aircAruvnKk',format:'watch',label:'essential',time:'19 min',published:'October 5, 2017',tags:['foundations'],why:'The visuals make a difficult core idea understandable without requiring code or advanced mathematics.',next:'Watch for the distinction between the inputs, hidden layers, and the final prediction.'},
    {title:'Thinking Like an AI',source:'One Useful Thing · Ethan Mollick',url:'https://www.oneusefulthing.org/p/thinking-like-an-ai',format:'read',label:'essential',time:'12 min',published:'October 20, 2024',tags:['foundations'],why:'A plain-language mental model for why language models can be surprisingly capable and still behave unpredictably.',next:'Spend ten hours bringing real, low-risk work to AI and keep notes on where it succeeds and fails.'},
    {title:'Getting Found in the AI Age: A Guide for Operators',source:'Arival · Oliver Green',url:'https://arival.travel/article/getting-found-in-the-ai-age-a-guide-for-operators/',format:'read',label:'reference',time:'15 min',published:'March 30, 2026',tags:['findability','marketing'],why:'A clear operator-level introduction to AI search, answer-engine optimization, third-party signals, and zero-click discovery.',next:'Search for your business as a traveler would and record which sources the answer cites—not only whether your website appears.'},
    {title:'Storytelling as a Competitive Advantage in the Age of AI',source:'Tourpreneur · Mitch Bach with Iain Manley',url:'https://tourpreneur.com/storytelling-as-a-competitive-advantage-in-the-age-of-ai/',format:'listen',label:'essential',time:'Podcast',published:'March 17, 2026',tags:['marketing'],why:'Personal perspective, specificity, and a real sense of place remain strong travel differentiators as generic AI content multiplies.',next:'Review one tour description or guide script and add a detail that could only come from firsthand knowledge.'}
  ],
  aiTools: [
    {name:'ChatGPT',company:'OpenAI',type:'General assistant',recommended:true,url:'https://chatgpt.com/',learnUrl:'https://academy.openai.com/',best:'A versatile first assistant for writing, planning, files, images, research, projects, and connected work.',start:'Bring one real recurring task. Give it a goal, context, desired output, and a clear boundary.'},
    {name:'Claude',company:'Anthropic',type:'General assistant',recommended:true,url:'https://claude.ai/',learnUrl:'https://www.anthropic.com/learn/claude-for-you',best:'Thoughtful work with long documents, analysis, writing, projects, and creating useful artifacts.',start:'Upload a non-sensitive document and ask for a summary, unanswered questions, and a fact-check list.'},
    {name:'Gemini',company:'Google',type:'General assistant',recommended:false,url:'https://gemini.google.com/',learnUrl:'https://support.google.com/gemini/answer/13275745?hl=en',best:'People who already work in the Google ecosystem and want an assistant for ideas, research, files, and media.',start:'Ask it to compare three ways to solve a familiar work problem, then verify the factual claims.'},
    {name:'Perplexity',company:'Perplexity',type:'Answer engine',recommended:true,url:'https://www.perplexity.ai/',learnUrl:'https://www.perplexity.ai/help-center/en/articles/10354975-getting-started-with-perplexity',best:'Current web research, exploring a question, following citations, and building a sourced starting point.',start:'Research one current travel question. Open at least three cited sources and note what the answer missed.'},
    {name:'Microsoft Copilot',company:'Microsoft',type:'Work assistant',recommended:false,url:'https://copilot.com/',learnUrl:'https://support.microsoft.com/en-us/microsoft-copilot/getting-started-with-microsoft-copilot',best:'People whose daily work already lives in Microsoft 365, Outlook, Word, Excel, PowerPoint, or Teams.',start:'Use a low-risk draft or document and ask Copilot to summarize it, identify gaps, and suggest next steps.'},
    {name:'Gemini Notebook (formerly NotebookLM)',company:'Google',type:'Source-grounded research',recommended:false,url:'https://notebooklm.google/',learnUrl:'https://support.google.com/notebooklm/answer/16164461?hl=en',best:'Learning from a defined collection of your own sources, with citations, study guides, and audio overviews.',start:'Create a notebook with two trusted sources and ask for agreements, disagreements, and cited takeaways.'}
  ],
  suggestedPath: [
    {name:'AI Fluency: Framework & Foundations',creator:'Anthropic',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',note:'Start with a durable framework for delegating, describing, judging, and responsibly using AI.'},
    {name:'Elements of AI',creator:'University of Helsinki + MinnaLearn',url:'https://www.elementsofai.com/',note:'Build a nontechnical foundation for what AI can and cannot do.'},
    {name:'Introduction to Generative AI',creator:'Google',url:'https://www.skills.google/course_templates/536',note:'Use a short primer to distinguish generative AI from earlier forms of machine learning.'},
    {name:'OpenAI Academy',creator:'OpenAI',url:'https://academy.openai.com/',note:'Practice applying an assistant to real work with current first-party instruction.'},
    {name:'AI for Marketers',creator:'HubSpot Academy',url:'https://academy.hubspot.com/courses/AI-for-Marketers',note:'Apply AI to content, email, social, and campaign work.'},
    {name:'Generative AI for Everyone',creator:'DeepLearning.AI · Andrew Ng',url:'https://www.coursera.org/learn/generative-ai-for-everyone',note:'Finish with a calm business-strategy view of where generative AI creates value.'}
  ],
  glossary: [
    {term:'Artificial intelligence (AI)',definition:'The broad field of making computers perform tasks that normally require human-like perception, language, prediction, or decision-making.'},
    {term:'Generative AI',definition:'AI that creates new material—such as text, images, audio, video, or code—based on patterns learned from examples.'},
    {term:'Large language model (LLM)',definition:'A model trained on large amounts of language so it can interpret and generate text. It predicts plausible language; it does not “know” facts the way a person does.'},
    {term:'Model',definition:'The underlying trained system. A product such as ChatGPT may offer several models with different strengths, speeds, or limits.'},
    {term:'AI assistant',definition:'The product interface you talk to, such as ChatGPT, Claude, or Gemini. The assistant can combine a model with tools, memory, files, and safety controls.'},
    {term:'Multimodal',definition:'Able to work with more than one kind of input or output, such as text, images, audio, or video.'},
    {term:'Prompt',definition:'The instruction, question, examples, files, and context you give an AI. A useful prompt states the goal, relevant context, desired output, and boundaries.'},
    {term:'Context',definition:'The information available to the model for the current task, including your prompt, conversation, attached files, and permitted connected data.'},
    {term:'Context window',definition:'The amount of information a model can consider at one time. Older or less relevant material may fall outside it in very long conversations.'},
    {term:'Token',definition:'A small chunk of text processed by a model. Usage limits and context windows are often measured in tokens rather than words.'},
    {term:'Hallucination',definition:'A confident-sounding AI statement that is unsupported, invented, or incorrect. Important facts should be checked against reliable sources.'},
    {term:'Grounding',definition:'Tying an answer to supplied files, reliable web sources, or connected data instead of relying only on the model’s general training.'},
    {term:'Retrieval / RAG',definition:'Finding relevant information first and giving it to the model to use in its answer. RAG stands for retrieval-augmented generation.'},
    {term:'Agent',definition:'An AI system that can plan steps and use tools to pursue an outcome, often with checkpoints or approvals. More autonomy requires clearer boundaries and review.'},
    {term:'Connection / connector',definition:'An authorized link between an AI assistant and another service, allowing supported reading, searching, syncing, or actions within the permissions granted.'},
    {term:'Plugin',definition:'A packaged workflow that can add instructions, connected apps, or tools to ChatGPT or Codex. Installing it does not automatically grant access to an outside account.'},
    {term:'Skill',definition:'Reusable instructions that teach an AI how to perform a particular kind of task consistently. A skill may not require any outside connection.'},
    {term:'MCP',definition:'Model Context Protocol—a standard that lets AI products use approved external tools and information through a defined connection.'},
    {term:'API',definition:'A structured way for one piece of software to request data or actions from another. APIs are commonly used to put AI inside an app or workflow.'},
    {term:'Memory',definition:'Information an AI product may retain to personalize future conversations. Memory controls, scope, and availability vary by product and account.'},
    {term:'Deep research',definition:'A longer research workflow in which an AI searches multiple sources, synthesizes findings, and usually provides citations for review.'},
    {term:'Fine-tuning',definition:'Additional training that adapts a model to examples of a specific task or style. Most beginners do not need fine-tuning to use AI effectively.'}
  ],
  trustedSources: [
    {name:'Everything AI in Travel',kind:'podcast',url:'https://www.everythingaiintravel.com/blog',note:'Travel-specific interviews, analysis, and practical operator examples.'},
    {name:'Travel Trends Podcast',kind:'podcast',url:'https://www.traveltrendspodcast.com/',note:'B2B conversations about discovery, booking, distribution, and travel technology.'},
    {name:'Tourpreneur',kind:'podcast',url:'https://tourpreneur.com/',note:'Grounded operator conversations about marketing, operations, and guest experience.'},
    {name:'In Phocus',kind:'podcast',url:'https://www.phocuswire.com/In-Phocus-Podcast',note:'Travel-tech news and interviews from PhocusWire.'},
    {name:'The AI Daily Brief',kind:'podcast',url:'https://aidailybrief.ai/',note:'Fast context on major AI changes; individual episodes are vetted before featuring.'},
    {name:'3Blue1Brown',kind:'youtube',url:'https://www.youtube.com/@3blue1brown',note:'Exceptional visual explanations of neural networks and machine learning foundations.'},
    {name:'DeepLearning.AI',kind:'youtube',url:'https://www.youtube.com/@Deeplearningai',note:'Short explainers, interviews, and selected practical AI lessons.'},
    {name:'Andrej Karpathy',kind:'youtube',url:'https://www.youtube.com/@AndrejKarpathy',note:'Long-form, build-from-first-principles explanations for deeper technical learning.'},
    {name:'Two Minute Papers',kind:'youtube',url:'https://www.youtube.com/@TwoMinutePapers',note:'Accessible summaries of new AI research; use for orientation, not business decisions.'},
    {name:'One Useful Thing',kind:'newsletter',url:'https://www.oneusefulthing.org/',note:'Evidence-led guidance for using AI thoughtfully at work.'},
    {name:'Travel Tech Essentialist',kind:'newsletter',url:'https://traveltechessentialist.substack.com/',note:'Travel-platform, investment, and technology-shift analysis.'},
    {name:'AI Snake Oil',kind:'newsletter',url:'https://www.aisnakeoil.com/',note:'A valuable skeptical lens for evaluating AI claims and risks.'},
    {name:'The Batch',kind:'newsletter',url:'https://www.deeplearning.ai/the-batch/',note:'Weekly expert framing of important AI developments.'},
    {name:'OpenAI Academy',kind:'learning',url:'https://academy.openai.com/',note:'Current first-party learning for ChatGPT, Codex, work, and small business.'},
    {name:'Anthropic AI Fluency',kind:'learning',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',note:'A practical, model-independent framework for collaborating with AI.'},
    {name:'Elements of AI',kind:'learning',url:'https://www.elementsofai.com/',note:'A durable, nontechnical introduction to AI.'},
    {name:'Arival',kind:'web',url:'https://arival.travel/',note:'Research and practical guidance for tours, activities, attractions, and experiences.'},
    {name:'PhocusWire',kind:'web',url:'https://www.phocuswire.com/',note:'Travel technology, distribution, platforms, and industry analysis.'}
    ,{name:'The Artificial Intelligence Show',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/the-artificial-intelligence-show/id1548733275',note:'Paul Roetzer and Mike Kaput translate weekly AI news into practical business implications with unusually consistent, relevant analysis.'}
    ,{name:'AI-Driven Marketer',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/ai-driven-marketer-master-practical-ai-marketing-skills/id1719663520',note:'Dan Sanchez shares practical AI marketing tools, workflows, copy, and campaign lessons.'}
    ,{name:'Small Business Big AI',kind:'podcast',url:'https://podcasts.apple.com/us/podcast/small-business-big-ai/id1768659876',note:'Kim Lewis Howard focuses on strategy, governance, and high-value AI workflows for small businesses.'}
    ,{name:'Matt Wolfe',kind:'youtube',url:'https://www.youtube.com/results?search_query=matt+wolfe+ai',note:'Matt Wolfe publishes frequent visual roundups of new AI tools and releases; use recent videos for orientation, then verify product claims.'}
    ,{name:'Superhuman AI',kind:'newsletter',url:'https://www.superhuman.ai/',note:'Zain Kahn and the Superhuman team publish a short daily briefing on AI tools and news.'}
    ,{name:'Sabrina Ramonov',kind:'youtube',url:'https://www.youtube.com/results?search_query=sabrina+ramonov+ai',note:'Sabrina Ramonov shares prompts, playbooks, and automation systems suited to solo operators and lean teams.'}
    ,{name:'Behind the Craft',kind:'newsletter',url:'https://creatoreconomy.so/',note:'Peter Yang writes hands-on AI and go-to-market tutorials, including practical campaigns and workflows.'}
    ,{name:'Marketing podcasts for the AI and GEO era',kind:'web',url:'https://www.netranks.ai/blog/top-marketing-podcasts-for-the-ai-and-geo-era/',note:'NetRanks curates shows about AI search visibility; use it to find a current GEO-focused episode.'}
    ,{name:'Generative Engine Optimization: Complete Guide',kind:'web',url:'https://www.enrichlabs.ai/blog/generative-engine-optimization-geo-complete-guide-2026',note:'Enrich Labs explains how GEO differs from SEO and what can help a source earn citations in AI answers.'}
    ,{name:'GEO: How to rank in AI search',kind:'web',url:'https://llmpulse.ai/blog/geo-guide/',note:'LLM Pulse provides a second, practical view of visibility in generative search engines.'}
    ,{name:'Schema Markup Guide for SEO and AI Search',kind:'web',url:'https://discoverability.co/resources/schema-markup-guide/',note:'Discoverability explains structured data and the schema types most useful for machine-readable business information.'}
    ,{name:'Structured Data for AI Search',kind:'web',url:'https://www.stackmatix.com/blog/structured-data-ai-search',note:'Stackmatix shows how JSON-LD is generated and added to a website.'}
    ,{name:'Julian Goldie',kind:'youtube',url:'https://www.youtube.com/results?search_query=julian+goldie+schema+ai+seo',note:'Julian Goldie publishes frequent, practical videos about AI SEO, schema, and content workflows; verify fast-changing tactics before adopting them.'}
    ,{name:'Nate Herk',kind:'youtube',url:'https://www.youtube.com/results?search_query=nate+herk+ai+automation',note:'Nate Herk demonstrates end-to-end AI automations with n8n, making agent workflows visible and concrete.'}
    ,{name:'Best AI agents for marketing',kind:'web',url:'https://www.tofuhq.com/post/best-ai-agents-for-marketing',note:'Tofu HQ maps marketing-agent tools to their likely jobs; treat the vendor landscape as time-sensitive.'}
    ,{name:'How Generative AI Is Revolutionizing Travel and Tourism',kind:'web',url:'https://arival.travel/article/generative-ai-in-travel-tourism/',note:'Arival gives travel-specific examples of personalization, itinerary building, and AI assistance for travelers.'}
    ,{name:'Travel Trends for Tour Operators',kind:'web',url:'https://www.rezgo.com/blog/global-travel-trends-2026-what-tour-and-activity-operators-need-to-know/',note:'Rezgo offers an operator-focused view of AI and demand trends for tours and activities.'}
    ,{name:'Adventure Travel Education',kind:'web',url:'https://learn.adventuretravel.biz/education/',note:'The Adventure Travel Trade Association publishes education grounded in the adventure-travel community.'}
    ,{name:"There's An AI For That",kind:'web',url:'https://theresanaiforthat.com/',note:'A broad discovery directory for exploring AI tools; evaluate privacy, cost, and credibility before adopting anything listed.'}
    ,{name:'FutureTools',kind:'web',url:'https://www.futuretools.io/',note:'Matt Wolfe curates AI tools and news for quick discovery; verify current product details at the original source.'}
    ,{name:'Product Hunt: Artificial Intelligence',kind:'web',url:'https://www.producthunt.com/topics/artificial-intelligence',note:'A high-volume discovery feed for new AI products; useful for scanning, not as a quality endorsement.'}
    ,{name:'The Rundown AI',kind:'newsletter',url:'https://www.therundown.ai/',note:'A frequent, concise AI-news briefing for maintaining awareness of major releases.'}
    ,{name:"Ben's Bites",kind:'newsletter',url:'https://bensbites.com/',note:'Ben Tossell shares frequent AI product and workflow discoveries with a practical builder perspective.'}
    ,{name:'Introduction to Generative AI',kind:'learning',url:'https://www.skills.google/course_templates/536',note:'Google provides a short first-party introduction to generative AI and how it differs from traditional machine learning.'}
    ,{name:'AI for Marketers',kind:'learning',url:'https://academy.hubspot.com/courses/AI-for-Marketers',note:'HubSpot Academy teaches practical AI uses for content, email, social media, and campaign reporting.'}
    ,{name:'Generative AI for Everyone',kind:'learning',url:'https://www.coursera.org/learn/generative-ai-for-everyone',note:'Andrew Ng and DeepLearning.AI explain generative AI through a nontechnical business-strategy lens.'}
  ]
};
